server:
  port: 7000

spring:
  application.name: demo
  resources:
    add-mappings: false
  output.ansi.enabled: always # Show colored output
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      fail-on-unwrapped-type-identifiers: false
      indent-output: true
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  data:
    rest:
      base-path: /api
      return-body-on-create: true
      return-body-on-update: true
      max-page-size: 100
      default-page-size: 50
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE:100MB}
      max-request-size: ${MAX_UPLOAD_SIZE:100MB}
      enabled: true
